telefonicaid/perseo-core

rpm/get_version_string.sh

FIX text issues

---

CHANGES_NEXT_RELEASE
src/main/java/com/telefonica/iot/perseo/Configuration.java
src/main/java/com/telefonica/iot/perseo/Constants.java
src/main/java/com/telefonica/iot/perseo/EventsServlet.java
src/main/java/com/telefonica/iot/perseo/GenericListener.java
src/main/java/com/telefonica/iot/perseo/Result.java
src/main/java/com/telefonica/iot/perseo/RulesManager.java
src/main/java/com/telefonica/iot/perseo/RulesServlet.java
src/main/java/com/telefonica/iot/perseo/Utils.java
src/test/java/com/telefonica/iot/perseo/EventsServletTest.java
src/test/java/com/telefonica/iot/perseo/GenericListenerTest.java
src/test/java/com/telefonica/iot/perseo/RulesManagerTest.java
src/test/java/com/telefonica/iot/perseo/RulesServletTest.java
src/test/java/com/telefonica/iot/perseo/UtilsTest.java
src/test/java/com/telefonica/iot/perseo/test/EventBeanMock.java
src/test/java/com/telefonica/iot/perseo/test/Help.java
src/test/java/com/telefonica/iot/perseo/test/ServletContextMock.java

"Twin" PR for #7 
As "twin-ness chesksum" you can see, the diff count (+127 -63) is the same as in PR #7 
@crbrox

FIX corresponding to PR #7

---

pom.xml

To be considered by the Metrics team, not for Developers ;)
@frarape

Changing sonar key

---

CHANGES_NEXT_RELEASE
pom.xml

Include perseo-core.properties in WAR file

---

LICENSE
README.md
rpm/SOURCES/etc/cron.d/cron-logrotate-perseo-core-size
rpm/SOURCES/etc/logrotate.d/logrotate-perseo-core.conf
rpm/SOURCES/etc/sysconfig/logrotate-perseo-core-size
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh
rpm/get_version_string.sh
src/main/java/com/telefonica/iot/perseo/Configuration.java
src/main/java/com/telefonica/iot/perseo/Constants.java
src/main/java/com/telefonica/iot/perseo/EventsServlet.java
src/main/java/com/telefonica/iot/perseo/GenericListener.java
src/main/java/com/telefonica/iot/perseo/Result.java
src/main/java/com/telefonica/iot/perseo/RulesManager.java
src/main/java/com/telefonica/iot/perseo/RulesServlet.java
src/main/java/com/telefonica/iot/perseo/Utils.java
src/main/java/com/telefonica/iot/perseo/Version.java
src/main/resources/perseo-core.properties
src/main/webapp/index.jsp
src/main/webapp/reload.jsp
src/main/webapp/version.jsp
src/test/java/com/telefonica/iot/perseo/EventsServletTest.java
src/test/java/com/telefonica/iot/perseo/GenericListenerTest.java
src/test/java/com/telefonica/iot/perseo/RulesManagerTest.java
src/test/java/com/telefonica/iot/perseo/RulesServletTest.java
src/test/java/com/telefonica/iot/perseo/UtilsTest.java
src/test/java/com/telefonica/iot/perseo/test/EventBeanMock.java
src/test/java/com/telefonica/iot/perseo/test/Help.java
src/test/java/com/telefonica/iot/perseo/test/ServletContextMock.java

Checked that there aren't ocurrences to AGPv3 using:
```
grep -R Affero *
grep -R 'version 3' *
```

CHANGE license AGPv3 -> GPLv2

---

rpm/SOURCES/etc/cron.d/cron-logrotate-perseo-core-size
rpm/SOURCES/etc/logrotate.d/logrotate-perseo-core.conf
rpm/SOURCES/etc/sysconfig/logrotate-perseo-core-size
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh
rpm/get_version_string.sh
src/main/java/com/telefonica/iot/perseo/Configuration.java
src/main/java/com/telefonica/iot/perseo/Constants.java
src/main/java/com/telefonica/iot/perseo/EventsServlet.java
src/main/java/com/telefonica/iot/perseo/GenericListener.java
src/main/java/com/telefonica/iot/perseo/Result.java
src/main/java/com/telefonica/iot/perseo/RulesManager.java
src/main/java/com/telefonica/iot/perseo/RulesServlet.java
src/main/java/com/telefonica/iot/perseo/Utils.java
src/main/java/com/telefonica/iot/perseo/Version.java
src/main/resources/perseo-core.properties
src/main/webapp/index.jsp
src/main/webapp/reload.jsp
src/main/webapp/version.jsp
src/test/java/com/telefonica/iot/perseo/EventsServletTest.java
src/test/java/com/telefonica/iot/perseo/GenericListenerTest.java
src/test/java/com/telefonica/iot/perseo/RulesManagerTest.java
src/test/java/com/telefonica/iot/perseo/RulesServletTest.java
src/test/java/com/telefonica/iot/perseo/UtilsTest.java
src/test/java/com/telefonica/iot/perseo/test/EventBeanMock.java
src/test/java/com/telefonica/iot/perseo/test/Help.java
src/test/java/com/telefonica/iot/perseo/test/ServletContextMock.java

Check using
```
grep -R 'either version 2' *
grep -R 'any later' *
```
(Except LICENCE file)

FIX stick to GPLv2

---

CHANGES_NEXT_RELEASE
pom.xml
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh

Prepare the changes for the merge with master.

ADD Prepare for next release

---

rpm/get_version_string.sh

@fgalan @crbrox 
Changed the script get_version_string for adapt to tags "0.x.x-KO" instead of "0.x.x/KO"
Tested and working.

bugfix in get_version_string

---

rpm/get_version_string.sh

Reverts telefonicaid/perseo-core#27

Revert "bugfix in get_version_string"

---

rpm/SPECS/cep-core.spec

spec cep-core bugfix

---

rpm/SPECS/cep-core.spec

Twin PR of https://github.com/telefonicaid/perseo-core/pull/32
This branch should be deleted after merging.
@dmoranj or @robertocs

Bugfix/rpm package (into develop)

---

documentation/deployment.md

Adjust log directory

---

rpm/get_version_string.sh

Fix for getting the proper version name on develop branch

Fix bug for get the correct string on develop branch

---

pom.xml
rpm/SPECS/cep-core.spec

Step: 0.2.0-SNAPSHOT -> 0.3.0

---

rpm/SPECS/cep-core.spec
rpm/create-rpm.sh

Step 0.2.0-SNAPSHOT -> 0.3.0

---

documentation/deployment.md

FIX typo in doc

---

pom.xml
rpm/create-rpm.sh

Step: 0.3.0 -> 0.3.0-SNAPSHOT

---

src/test/java/com/telefonica/iot/perseo/test/Help.java

Hoping this is the problem

---

src/test/java/com/telefonica/iot/perseo/LogLevelServletTest.java

Second failing test in jenkins

---

src/test/java/com/telefonica/iot/perseo/LogLevelServletTest.java

True fix, my fault

---

CHANGES_NEXT_RELEASE
src/main/java/com/telefonica/iot/perseo/Constants.java
src/main/java/com/telefonica/iot/perseo/RulesServlet.java
src/main/java/com/telefonica/iot/perseo/Utils.java
src/main/resources/log4j.xml
src/test/resources/log4j.xml

Use srv/subsrv in logs

---

CHANGES_NEXT_RELEASE
src/main/java/com/telefonica/iot/perseo/Constants.java

Use fiware-correlator in header

---

CHANGES_NEXT_RELEASE
pom.xml
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh

Step 0.3.0-SNAPSHOT -> 1.0.0

---

Dockerfile

ADD Change DockerFile to Copy instead of clone

---

Dockerfile

ADD Change DockerFile to Copy instead of clone (releas/1.0.0)

---

pom.xml
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh

ADD: Step: 1.0.0 -> 1.0.1

---

CHANGES_NEXT_RELEASE

Corresponds to the change in PR #62 
@crbrox

ADD missing entry to CNR

---

src/main/resources/log4j.xml

Probado en el entono de integracion (interno)

fixed timestang string format ti end in Z instead of UTC

---

CHANGES_NEXT_RELEASE
pom.xml
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh

I've tried to reproduce the same changes that we did last time for this. Have a look to compare: https://github.com/telefonicaid/perseo-core/commit/539ac1ebab540ade06858ad68758bebc6a76c95e

Step: 1.0.0-SNAPSHOT -> 1.1.0

---

pom.xml
rpm/create-rpm.sh

Compere wiht the same task done last time: https://github.com/telefonicaid/perseo-core/commit/310fc91795e006d7582f9e8be5005399f4679ff5

Step: 1.1.0 -> 1.1.0-SNAPSHOT

---

CHANGES_NEXT_RELEASE
pom.xml

Fixes https://github.com/telefonicaid/perseo-core/issues/87

Upgrade Esper version to 6.1.0

---

CHANGES_NEXT_RELEASE
pom.xml
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh

Step: 1.1.0-SNAPSHOT -> 1.2.0

---

pom.xml
rpm/create-rpm.sh

Step: 1.2.0 -> 1.2.0-SNAPSHOT

---

Dockerfile
src/main/java/com/telefonica/iot/perseo/Configuration.java

This PR is a continuation of #100
Fix dockerfile deployment problems when 'http://' it is absent in PERSEO_FE env var or parameter.
Clean unnecessary files and packages in Dockerfile.

Dockerfile Improvements

---

Dockerfile

Fix in PR https://github.com/telefonicaid/perseo-core/pull/107 was wrong. This should be the rigth one :)
CC: @cblanco

FIX Dockerflie

---

Dockerfile

Use only 1 'RUN' in Dockerfile and remove JDK

improving Docker image size

---

CHANGES_NEXT_RELEASE
pom.xml

This reverts telefonicaid/perseo-core#111, so efectively restoring PR #101 by @cblanco

Revert "Revert "Update Dependencies""

---

pom.xml
rpm/create-rpm.sh

Mimics PR https://github.com/telefonicaid/perseo-core/pull/95
@cblanco. Once 1.3.0 has been frozen, this PR prepares the code for the development of the new one.

Step: 1.3.0 -> 1.3.0-SNAPSHOT

---

CHANGES_NEXT_RELEASE
perseo_core-entrypoint.sh

fix issue https://github.com/telefonicaid/perseo-core/issues/110

fix log for docker container

---

Dockerfile

This PR adds a healtcheck command in perseo's Dockerfile.

Add healthcheck command

---

CHANGES_NEXT_RELEASE
pom.xml
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh

Mimics PR https://github.com/telefonicaid/perseo-core/pull/119

Step: 1.3.0-SNAPSHOT -> 1.4.0

---

pom.xml
rpm/create-rpm.sh

Mimics PR https://github.com/telefonicaid/perseo-core/pull/120

Step: 1.4.0 -> 1.4.0-SNAPSHOT

---

perseo-main/src/main/java/com/telefonica/iot/perseo/Utils.java
perseo-utils/src/main/java/com/telefonica/iot/perseo/utils/DateTimeUtils.java

Restored previous library to avoid legacy issues.
Edited condition to compare dates on date time utils functions.

Fix/add previous libraries [DON'T MERGE]

---

CHANGES_NEXT_RELEASE
perseo-main/src/main/java/com/telefonica/iot/perseo/Utils.java

This PR adds disables cache on EPServiceProvider object.

disable cache on setup

---

perseo-utils/src/main/java/com/telefonica/iot/perseo/utils/DateTimeUtils.java
perseo-utils/src/test/java/com/telefonica/iot/perseo/utils/DateTimeUtilsTest.java

No CNR entry added cause it's a fix from previous PR.

convert time from current timestamp

---

CHANGES_NEXT_RELEASE
perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh

Mimics PR https://github.com/telefonicaid/perseo-core/pull/140

Step: 1.4.0-SNAPSHOT -> 1.5.0

---

perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/create-rpm.sh

Step: 1.5.0 -> 1.5.0-SNAPSHOT

---

Dockerfile

This PR updates the Dockerfile to be executed as non root user.

update Dockerfile to be executed as non root user

---

CHANGES_NEXT_RELEASE
perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh

Step: 1.5.0-SNAPSHOT -> 1.6.0

---

perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/create-rpm.sh

Step: 1.6.0 -> 1.6.0-SNAPSHOT

---

CHANGES_NEXT_RELEASE
perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh

Mimics PR https://github.com/telefonicaid/perseo-core/pull/161

Step: 1.6.0-SNAPSHOT -> 1.7.0

---

perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/create-rpm.sh

Mimics PR https://github.com/telefonicaid/perseo-core/pull/162

Step: 1.7.0 -> 1.7.0-SNAPSHOT

---

CHANGES_NEXT_RELEASE

FIX Esper version in CNR

---

CHANGES_NEXT_RELEASE
perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh

Step: 1.7.0-SNAPSHOT -> 1.8.0

---

perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/create-rpm.sh

Step: 1.8.0 -> 1.8.0-SNAPSHOT

---

CHANGES_NEXT_RELEASE
perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh

Mimics PR https://github.com/telefonicaid/perseo-core/pull/180

Step: 1.8.0-SNAPSHOT -> 1.9.0

---

perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/create-rpm.sh

Mimics PR https://github.com/telefonicaid/perseo-core/pull/181

Step: 1.9.0 -> 1.9.0-SNAPSHOT

---

CHANGES_NEXT_RELEASE
perseo-main/src/main/java/com/telefonica/iot/perseo/Utils.java

fix for https://github.com/telefonicaid/perseo-core/issues/200

use JSONObject.NULL when a null value is found

---

perseo-main/src/test/java/com/telefonica/iot/perseo/UtilsTest.java

continuation of PR https://github.com/telefonicaid/perseo-core/pull/201

add test case about use null value in an event

---

CHANGES_NEXT_RELEASE
perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh

Mimics PR https://github.com/telefonicaid/perseo-core/pull/198

Step: 1.9.0-SNAPSHOT -> 1.10.0

---

perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/create-rpm.sh

Step: 1.10.0 -> 1.10.0-SNAPSHOT

---

CHANGES_NEXT_RELEASE
perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh

Mimics PR https://github.com/telefonicaid/perseo-core/pull/203

Step: 1.10.0-SNAPSHOT -> 1.11.0

---

perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/create-rpm.sh

Step: 1.11.0 -> 1.11.0-SNAPSHOT

---

CHANGES_NEXT_RELEASE
perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/SPECS/cep-core.spec
rpm/create-rpm.sh

Mimics PR https://github.com/telefonicaid/perseo-core/pull/206

Step: 1.11.0-SNAPSHOT -> 1.12.0

---

perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/create-rpm.sh

step 1.12.0 -> 1.12.0-snapshot

---

CHANGES_NEXT_RELEASE
perseo-main/src/main/java/com/telefonica/iot/perseo/Utils.java

fix for https://github.com/telefonicaid/perseo-core/issues/217

Update Utils.java: add java.lang.* and java.util.* imports

---

CHANGES_NEXT_RELEASE
perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml
rpm/SPECS/cep-core.spec

Mimics PR https://github.com/telefonicaid/perseo-core/pull/211

step: 1.12.0-snapshot -> 1.13.0

---

.readthedocs.yml
documentation/requirements.txt

Align with https://github.com/telefonicaid/fiware-orion/blob/master/.readthedocs.yml
Add missing documentation/requirements.txt

FIX .readthedocs.yml

---

CHANGES_NEXT_RELEASE
Changelog
perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml

mimics https://github.com/telefonicaid/perseo-core/pull/220/

step: 1.13.0-snapshot -> 1.14.0

---

perseo-main/pom.xml
perseo-utils/pom.xml
pom.xml

Mimics https://github.com/telefonicaid/perseo-core/pull/221

step 1.14.0 -> 1.14.0-snapshot
